
name: Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # roda uma vez por dia
  workflow_dispatch:     # permite rodar manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate snake.svg

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate the snake
        uses: Platane/snk@v3
        with:
          github_user_name: Katana2d-sama
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark&color_snake=#ff3c3c

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
